language: python
python:
  - "3.6"
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install pytest-cov
    - pip install coveralls
    - pip install lxml
    - pip install html5lib
# command to run tests
script: pytest tests/ --cov=.
after_success:
    - coveralls
